name: Build and Release

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CNAME: world.thingy.rocks
  WEBSOCKET_ENDPOINT: wss://gqhubutcb1.execute-api.us-west-2.amazonaws.com/2022-11-22
  MAP_NAME: thing-rocks-backend-map
  COGNITO_IDENTITY_POOL_ID: us-west-2:7318eb01-32ec-4bc1-b5e1-9d1a7719c4b5
  SENTRY_DSN: https://f0636caa395147fcb07f781d0c1e8e6c@o4504255385174016.ingest.sentry.io/4504255391596544

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build
        env:
          VERSION: ${{ github.sha }}
        run: npm run build

      - name: Publish to GitHub pages
        if: github.ref == 'refs/heads/saga'
        working-directory: build
        run: |
          echo "machine github.com login accesskey password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
          git config --global user.email "actions@example.com"
          git config --global user.name "github-actions[bot]"
          git config --global init.defaultBranch gh-pages
          touch .nojekyll
          cp -r ../static ./
          echo ${{ env.CNAME }} > CNAME
          git init
          git add -A
          git commit -m "update website"
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git push -f origin HEAD:gh-pages
