name: Build and Release

on:
  push:
    branches: ["saga"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

env:
  CNAME: world.thingy.rocks
  WEBSOCKET_ENDPOINT: wss://gqhubutcb1.execute-api.us-west-2.amazonaws.com/2022-11-22
  MAP_NAME: thingy-rocks-backend-map
  COGNITO_IDENTITY_POOL_ID: us-west-2:7318eb01-32ec-4bc1-b5e1-9d1a7719c4b5
  SENTRY_DSN: https://f0636caa395147fcb07f781d0c1e8e6c@o4504255385174016.ingest.sentry.io/4504255391596544

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build
        env:
          VERSION: ${{ github.sha }}
        run: |
          npm run build
          cp -r ./static ./build

      - name: Deploy to CloudFlare pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run:
          wrangler pages publish build --project-name thingy-world --branch saga
          --commit-hash ${{ github.sha }}

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        run: npx semantic-release
